/**
 * The one Worker binding this site reaches for: the static-asset store,
 * declared in wrangler.jsonc and used by src/start.ts to serve the
 * prerendered homepage after the Worker has claimed `/`.
 *
 * Hand-written rather than generated by `wrangler types`, which emits a
 * whole runtime type surface (and a file to keep in sync) for a binding
 * used in exactly one place. `env` is typed as what we actually read from
 * it — the binding is optional here because this module is also evaluated
 * during the build's prerender pass.
 */
declare module 'cloudflare:workers' {
  export const env: {
    ASSETS?: { fetch: (request: Request) => Promise<Response> };
  };
}
