/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as CategoryRailRouteImport } from './routes/category-rail'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as FilterChipsRouteImport } from './routes/filter-chips'
import { Route as NetflixRowRouteImport } from './routes/netflix-row'
import { Route as ScrollableTabsRouteImport } from './routes/scrollable-tabs'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleCategoryRailRouteImport } from './routes/$locale/category-rail'
import { Route as LocaleCompareRouteImport } from './routes/$locale/compare'
import { Route as LocaleFilterChipsRouteImport } from './routes/$locale/filter-chips'
import { Route as LocaleNetflixRowRouteImport } from './routes/$locale/netflix-row'
import { Route as LocaleScrollableTabsRouteImport } from './routes/$locale/scrollable-tabs'
import { Route as CompareEmblaVsSwiperRouteImport } from './routes/compare_.embla-vs-swiper'
import { Route as CompareReactSlickAlternativesRouteImport } from './routes/compare_.react-slick-alternatives'
import { Route as CompareSwiperAlternativesRouteImport } from './routes/compare_.swiper-alternatives'
import { Route as ExamplesIndexRouteImport } from './routes/examples/index'
import { Route as ExamplesAddItemAndScrollToItRouteImport } from './routes/examples/add-item-and-scroll-to-it'
import { Route as ExamplesAddItemsRouteImport } from './routes/examples/add-items'
import { Route as ExamplesAutoplayRouteImport } from './routes/examples/autoplay'
import { Route as ExamplesBottomArrowsRouteImport } from './routes/examples/bottom-arrows'
import { Route as ExamplesCenterOnClickRouteImport } from './routes/examples/center-on-click'
import { Route as ExamplesCustomTransitionRouteImport } from './routes/examples/custom-transition'
import { Route as ExamplesInfiniteLoopRouteImport } from './routes/examples/infinite-loop'
import { Route as ExamplesItemsAnimationRouteImport } from './routes/examples/items-animation'
import { Route as ExamplesMobileSwipeOnlyRouteImport } from './routes/examples/mobile-swipe-only'
import { Route as ExamplesMouseDragRouteImport } from './routes/examples/mouse-drag'
import { Route as ExamplesMuiScrollableTabsRouteImport } from './routes/examples/mui-scrollable-tabs'
import { Route as ExamplesOneItemRouteImport } from './routes/examples/one-item'
import { Route as ExamplesOneItemScrollRouteImport } from './routes/examples/one-item-scroll'
import { Route as ExamplesPerformanceRouteImport } from './routes/examples/performance'
import { Route as ExamplesPreventBodyScrollRouteImport } from './routes/examples/prevent-body-scroll'
import { Route as ExamplesProgressRouteImport } from './routes/examples/progress'
import { Route as ExamplesRtlRouteImport } from './routes/examples/rtl'
import { Route as ExamplesSaveRestorePositionRouteImport } from './routes/examples/save-restore-position'
import { Route as ExamplesScrollToItemRouteImport } from './routes/examples/scroll-to-item'
import { Route as ExamplesSimpleRouteImport } from './routes/examples/simple'
import { Route as ExamplesSwipeDesktopRouteImport } from './routes/examples/swipe-desktop'
import { Route as ExamplesVerticalRouteImport } from './routes/examples/vertical'
import { Route as LocaleCompareEmblaVsSwiperRouteImport } from './routes/$locale/compare_.embla-vs-swiper'
import { Route as LocaleCompareReactSlickAlternativesRouteImport } from './routes/$locale/compare_.react-slick-alternatives'
import { Route as LocaleCompareSwiperAlternativesRouteImport } from './routes/$locale/compare_.swiper-alternatives'
import { Route as LocaleExamplesIndexRouteImport } from './routes/$locale/examples/index'
import { Route as LocaleExamplesAddItemAndScrollToItRouteImport } from './routes/$locale/examples/add-item-and-scroll-to-it'
import { Route as LocaleExamplesAddItemsRouteImport } from './routes/$locale/examples/add-items'
import { Route as LocaleExamplesAutoplayRouteImport } from './routes/$locale/examples/autoplay'
import { Route as LocaleExamplesBottomArrowsRouteImport } from './routes/$locale/examples/bottom-arrows'
import { Route as LocaleExamplesCenterOnClickRouteImport } from './routes/$locale/examples/center-on-click'
import { Route as LocaleExamplesCustomTransitionRouteImport } from './routes/$locale/examples/custom-transition'
import { Route as LocaleExamplesInfiniteLoopRouteImport } from './routes/$locale/examples/infinite-loop'
import { Route as LocaleExamplesItemsAnimationRouteImport } from './routes/$locale/examples/items-animation'
import { Route as LocaleExamplesMobileSwipeOnlyRouteImport } from './routes/$locale/examples/mobile-swipe-only'
import { Route as LocaleExamplesMouseDragRouteImport } from './routes/$locale/examples/mouse-drag'
import { Route as LocaleExamplesMuiScrollableTabsRouteImport } from './routes/$locale/examples/mui-scrollable-tabs'
import { Route as LocaleExamplesOneItemRouteImport } from './routes/$locale/examples/one-item'
import { Route as LocaleExamplesOneItemScrollRouteImport } from './routes/$locale/examples/one-item-scroll'
import { Route as LocaleExamplesPerformanceRouteImport } from './routes/$locale/examples/performance'
import { Route as LocaleExamplesPreventBodyScrollRouteImport } from './routes/$locale/examples/prevent-body-scroll'
import { Route as LocaleExamplesProgressRouteImport } from './routes/$locale/examples/progress'
import { Route as LocaleExamplesRtlRouteImport } from './routes/$locale/examples/rtl'
import { Route as LocaleExamplesSaveRestorePositionRouteImport } from './routes/$locale/examples/save-restore-position'
import { Route as LocaleExamplesScrollToItemRouteImport } from './routes/$locale/examples/scroll-to-item'
import { Route as LocaleExamplesSimpleRouteImport } from './routes/$locale/examples/simple'
import { Route as LocaleExamplesSwipeDesktopRouteImport } from './routes/$locale/examples/swipe-desktop'
import { Route as LocaleExamplesVerticalRouteImport } from './routes/$locale/examples/vertical'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRailRoute = CategoryRailRouteImport.update({
  id: '/category-rail',
  path: '/category-rail',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FilterChipsRoute = FilterChipsRouteImport.update({
  id: '/filter-chips',
  path: '/filter-chips',
  getParentRoute: () => rootRouteImport,
} as any)
const NetflixRowRoute = NetflixRowRouteImport.update({
  id: '/netflix-row',
  path: '/netflix-row',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrollableTabsRoute = ScrollableTabsRouteImport.update({
  id: '/scrollable-tabs',
  path: '/scrollable-tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCategoryRailRoute = LocaleCategoryRailRouteImport.update({
  id: '/category-rail',
  path: '/category-rail',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleCompareRoute = LocaleCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleFilterChipsRoute = LocaleFilterChipsRouteImport.update({
  id: '/filter-chips',
  path: '/filter-chips',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleNetflixRowRoute = LocaleNetflixRowRouteImport.update({
  id: '/netflix-row',
  path: '/netflix-row',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleScrollableTabsRoute = LocaleScrollableTabsRouteImport.update({
  id: '/scrollable-tabs',
  path: '/scrollable-tabs',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const CompareEmblaVsSwiperRoute = CompareEmblaVsSwiperRouteImport.update({
  id: '/compare_/embla-vs-swiper',
  path: '/compare/embla-vs-swiper',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareReactSlickAlternativesRoute =
  CompareReactSlickAlternativesRouteImport.update({
    id: '/compare_/react-slick-alternatives',
    path: '/compare/react-slick-alternatives',
    getParentRoute: () => rootRouteImport,
  } as any)
const CompareSwiperAlternativesRoute =
  CompareSwiperAlternativesRouteImport.update({
    id: '/compare_/swiper-alternatives',
    path: '/compare/swiper-alternatives',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesIndexRoute = ExamplesIndexRouteImport.update({
  id: '/examples/',
  path: '/examples/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesAddItemAndScrollToItRoute =
  ExamplesAddItemAndScrollToItRouteImport.update({
    id: '/examples/add-item-and-scroll-to-it',
    path: '/examples/add-item-and-scroll-to-it',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesAddItemsRoute = ExamplesAddItemsRouteImport.update({
  id: '/examples/add-items',
  path: '/examples/add-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesAutoplayRoute = ExamplesAutoplayRouteImport.update({
  id: '/examples/autoplay',
  path: '/examples/autoplay',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesBottomArrowsRoute = ExamplesBottomArrowsRouteImport.update({
  id: '/examples/bottom-arrows',
  path: '/examples/bottom-arrows',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesCenterOnClickRoute = ExamplesCenterOnClickRouteImport.update({
  id: '/examples/center-on-click',
  path: '/examples/center-on-click',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesCustomTransitionRoute =
  ExamplesCustomTransitionRouteImport.update({
    id: '/examples/custom-transition',
    path: '/examples/custom-transition',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesInfiniteLoopRoute = ExamplesInfiniteLoopRouteImport.update({
  id: '/examples/infinite-loop',
  path: '/examples/infinite-loop',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesItemsAnimationRoute = ExamplesItemsAnimationRouteImport.update({
  id: '/examples/items-animation',
  path: '/examples/items-animation',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesMobileSwipeOnlyRoute = ExamplesMobileSwipeOnlyRouteImport.update({
  id: '/examples/mobile-swipe-only',
  path: '/examples/mobile-swipe-only',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesMouseDragRoute = ExamplesMouseDragRouteImport.update({
  id: '/examples/mouse-drag',
  path: '/examples/mouse-drag',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesMuiScrollableTabsRoute =
  ExamplesMuiScrollableTabsRouteImport.update({
    id: '/examples/mui-scrollable-tabs',
    path: '/examples/mui-scrollable-tabs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesOneItemRoute = ExamplesOneItemRouteImport.update({
  id: '/examples/one-item',
  path: '/examples/one-item',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesOneItemScrollRoute = ExamplesOneItemScrollRouteImport.update({
  id: '/examples/one-item-scroll',
  path: '/examples/one-item-scroll',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesPerformanceRoute = ExamplesPerformanceRouteImport.update({
  id: '/examples/performance',
  path: '/examples/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesPreventBodyScrollRoute =
  ExamplesPreventBodyScrollRouteImport.update({
    id: '/examples/prevent-body-scroll',
    path: '/examples/prevent-body-scroll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesProgressRoute = ExamplesProgressRouteImport.update({
  id: '/examples/progress',
  path: '/examples/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesRtlRoute = ExamplesRtlRouteImport.update({
  id: '/examples/rtl',
  path: '/examples/rtl',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSaveRestorePositionRoute =
  ExamplesSaveRestorePositionRouteImport.update({
    id: '/examples/save-restore-position',
    path: '/examples/save-restore-position',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExamplesScrollToItemRoute = ExamplesScrollToItemRouteImport.update({
  id: '/examples/scroll-to-item',
  path: '/examples/scroll-to-item',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSimpleRoute = ExamplesSimpleRouteImport.update({
  id: '/examples/simple',
  path: '/examples/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesSwipeDesktopRoute = ExamplesSwipeDesktopRouteImport.update({
  id: '/examples/swipe-desktop',
  path: '/examples/swipe-desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesVerticalRoute = ExamplesVerticalRouteImport.update({
  id: '/examples/vertical',
  path: '/examples/vertical',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleCompareEmblaVsSwiperRoute =
  LocaleCompareEmblaVsSwiperRouteImport.update({
    id: '/compare_/embla-vs-swiper',
    path: '/compare/embla-vs-swiper',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleCompareReactSlickAlternativesRoute =
  LocaleCompareReactSlickAlternativesRouteImport.update({
    id: '/compare_/react-slick-alternatives',
    path: '/compare/react-slick-alternatives',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleCompareSwiperAlternativesRoute =
  LocaleCompareSwiperAlternativesRouteImport.update({
    id: '/compare_/swiper-alternatives',
    path: '/compare/swiper-alternatives',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesIndexRoute = LocaleExamplesIndexRouteImport.update({
  id: '/examples/',
  path: '/examples/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleExamplesAddItemAndScrollToItRoute =
  LocaleExamplesAddItemAndScrollToItRouteImport.update({
    id: '/examples/add-item-and-scroll-to-it',
    path: '/examples/add-item-and-scroll-to-it',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesAddItemsRoute = LocaleExamplesAddItemsRouteImport.update({
  id: '/examples/add-items',
  path: '/examples/add-items',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleExamplesAutoplayRoute = LocaleExamplesAutoplayRouteImport.update({
  id: '/examples/autoplay',
  path: '/examples/autoplay',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleExamplesBottomArrowsRoute =
  LocaleExamplesBottomArrowsRouteImport.update({
    id: '/examples/bottom-arrows',
    path: '/examples/bottom-arrows',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesCenterOnClickRoute =
  LocaleExamplesCenterOnClickRouteImport.update({
    id: '/examples/center-on-click',
    path: '/examples/center-on-click',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesCustomTransitionRoute =
  LocaleExamplesCustomTransitionRouteImport.update({
    id: '/examples/custom-transition',
    path: '/examples/custom-transition',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesInfiniteLoopRoute =
  LocaleExamplesInfiniteLoopRouteImport.update({
    id: '/examples/infinite-loop',
    path: '/examples/infinite-loop',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesItemsAnimationRoute =
  LocaleExamplesItemsAnimationRouteImport.update({
    id: '/examples/items-animation',
    path: '/examples/items-animation',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesMobileSwipeOnlyRoute =
  LocaleExamplesMobileSwipeOnlyRouteImport.update({
    id: '/examples/mobile-swipe-only',
    path: '/examples/mobile-swipe-only',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesMouseDragRoute = LocaleExamplesMouseDragRouteImport.update({
  id: '/examples/mouse-drag',
  path: '/examples/mouse-drag',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleExamplesMuiScrollableTabsRoute =
  LocaleExamplesMuiScrollableTabsRouteImport.update({
    id: '/examples/mui-scrollable-tabs',
    path: '/examples/mui-scrollable-tabs',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesOneItemRoute = LocaleExamplesOneItemRouteImport.update({
  id: '/examples/one-item',
  path: '/examples/one-item',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleExamplesOneItemScrollRoute =
  LocaleExamplesOneItemScrollRouteImport.update({
    id: '/examples/one-item-scroll',
    path: '/examples/one-item-scroll',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesPerformanceRoute =
  LocaleExamplesPerformanceRouteImport.update({
    id: '/examples/performance',
    path: '/examples/performance',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesPreventBodyScrollRoute =
  LocaleExamplesPreventBodyScrollRouteImport.update({
    id: '/examples/prevent-body-scroll',
    path: '/examples/prevent-body-scroll',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesProgressRoute = LocaleExamplesProgressRouteImport.update({
  id: '/examples/progress',
  path: '/examples/progress',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleExamplesRtlRoute = LocaleExamplesRtlRouteImport.update({
  id: '/examples/rtl',
  path: '/examples/rtl',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleExamplesSaveRestorePositionRoute =
  LocaleExamplesSaveRestorePositionRouteImport.update({
    id: '/examples/save-restore-position',
    path: '/examples/save-restore-position',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesScrollToItemRoute =
  LocaleExamplesScrollToItemRouteImport.update({
    id: '/examples/scroll-to-item',
    path: '/examples/scroll-to-item',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesSimpleRoute = LocaleExamplesSimpleRouteImport.update({
  id: '/examples/simple',
  path: '/examples/simple',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleExamplesSwipeDesktopRoute =
  LocaleExamplesSwipeDesktopRouteImport.update({
    id: '/examples/swipe-desktop',
    path: '/examples/swipe-desktop',
    getParentRoute: () => LocaleRouteRoute,
  } as any)
const LocaleExamplesVerticalRoute = LocaleExamplesVerticalRouteImport.update({
  id: '/examples/vertical',
  path: '/examples/vertical',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/category-rail': typeof CategoryRailRoute
  '/compare': typeof CompareRoute
  '/filter-chips': typeof FilterChipsRoute
  '/netflix-row': typeof NetflixRowRoute
  '/scrollable-tabs': typeof ScrollableTabsRoute
  '/$locale/category-rail': typeof LocaleCategoryRailRoute
  '/$locale/compare': typeof LocaleCompareRoute
  '/$locale/filter-chips': typeof LocaleFilterChipsRoute
  '/$locale/netflix-row': typeof LocaleNetflixRowRoute
  '/$locale/scrollable-tabs': typeof LocaleScrollableTabsRoute
  '/compare/embla-vs-swiper': typeof CompareEmblaVsSwiperRoute
  '/compare/react-slick-alternatives': typeof CompareReactSlickAlternativesRoute
  '/compare/swiper-alternatives': typeof CompareSwiperAlternativesRoute
  '/examples/add-item-and-scroll-to-it': typeof ExamplesAddItemAndScrollToItRoute
  '/examples/add-items': typeof ExamplesAddItemsRoute
  '/examples/autoplay': typeof ExamplesAutoplayRoute
  '/examples/bottom-arrows': typeof ExamplesBottomArrowsRoute
  '/examples/center-on-click': typeof ExamplesCenterOnClickRoute
  '/examples/custom-transition': typeof ExamplesCustomTransitionRoute
  '/examples/infinite-loop': typeof ExamplesInfiniteLoopRoute
  '/examples/items-animation': typeof ExamplesItemsAnimationRoute
  '/examples/mobile-swipe-only': typeof ExamplesMobileSwipeOnlyRoute
  '/examples/mouse-drag': typeof ExamplesMouseDragRoute
  '/examples/mui-scrollable-tabs': typeof ExamplesMuiScrollableTabsRoute
  '/examples/one-item': typeof ExamplesOneItemRoute
  '/examples/one-item-scroll': typeof ExamplesOneItemScrollRoute
  '/examples/performance': typeof ExamplesPerformanceRoute
  '/examples/prevent-body-scroll': typeof ExamplesPreventBodyScrollRoute
  '/examples/progress': typeof ExamplesProgressRoute
  '/examples/rtl': typeof ExamplesRtlRoute
  '/examples/save-restore-position': typeof ExamplesSaveRestorePositionRoute
  '/examples/scroll-to-item': typeof ExamplesScrollToItemRoute
  '/examples/simple': typeof ExamplesSimpleRoute
  '/examples/swipe-desktop': typeof ExamplesSwipeDesktopRoute
  '/examples/vertical': typeof ExamplesVerticalRoute
  '/$locale/': typeof LocaleIndexRoute
  '/examples/': typeof ExamplesIndexRoute
  '/$locale/compare/embla-vs-swiper': typeof LocaleCompareEmblaVsSwiperRoute
  '/$locale/compare/react-slick-alternatives': typeof LocaleCompareReactSlickAlternativesRoute
  '/$locale/compare/swiper-alternatives': typeof LocaleCompareSwiperAlternativesRoute
  '/$locale/examples/add-item-and-scroll-to-it': typeof LocaleExamplesAddItemAndScrollToItRoute
  '/$locale/examples/add-items': typeof LocaleExamplesAddItemsRoute
  '/$locale/examples/autoplay': typeof LocaleExamplesAutoplayRoute
  '/$locale/examples/bottom-arrows': typeof LocaleExamplesBottomArrowsRoute
  '/$locale/examples/center-on-click': typeof LocaleExamplesCenterOnClickRoute
  '/$locale/examples/custom-transition': typeof LocaleExamplesCustomTransitionRoute
  '/$locale/examples/infinite-loop': typeof LocaleExamplesInfiniteLoopRoute
  '/$locale/examples/items-animation': typeof LocaleExamplesItemsAnimationRoute
  '/$locale/examples/mobile-swipe-only': typeof LocaleExamplesMobileSwipeOnlyRoute
  '/$locale/examples/mouse-drag': typeof LocaleExamplesMouseDragRoute
  '/$locale/examples/mui-scrollable-tabs': typeof LocaleExamplesMuiScrollableTabsRoute
  '/$locale/examples/one-item': typeof LocaleExamplesOneItemRoute
  '/$locale/examples/one-item-scroll': typeof LocaleExamplesOneItemScrollRoute
  '/$locale/examples/performance': typeof LocaleExamplesPerformanceRoute
  '/$locale/examples/prevent-body-scroll': typeof LocaleExamplesPreventBodyScrollRoute
  '/$locale/examples/progress': typeof LocaleExamplesProgressRoute
  '/$locale/examples/rtl': typeof LocaleExamplesRtlRoute
  '/$locale/examples/save-restore-position': typeof LocaleExamplesSaveRestorePositionRoute
  '/$locale/examples/scroll-to-item': typeof LocaleExamplesScrollToItemRoute
  '/$locale/examples/simple': typeof LocaleExamplesSimpleRoute
  '/$locale/examples/swipe-desktop': typeof LocaleExamplesSwipeDesktopRoute
  '/$locale/examples/vertical': typeof LocaleExamplesVerticalRoute
  '/$locale/examples/': typeof LocaleExamplesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/category-rail': typeof CategoryRailRoute
  '/compare': typeof CompareRoute
  '/filter-chips': typeof FilterChipsRoute
  '/netflix-row': typeof NetflixRowRoute
  '/scrollable-tabs': typeof ScrollableTabsRoute
  '/$locale/category-rail': typeof LocaleCategoryRailRoute
  '/$locale/compare': typeof LocaleCompareRoute
  '/$locale/filter-chips': typeof LocaleFilterChipsRoute
  '/$locale/netflix-row': typeof LocaleNetflixRowRoute
  '/$locale/scrollable-tabs': typeof LocaleScrollableTabsRoute
  '/compare/embla-vs-swiper': typeof CompareEmblaVsSwiperRoute
  '/compare/react-slick-alternatives': typeof CompareReactSlickAlternativesRoute
  '/compare/swiper-alternatives': typeof CompareSwiperAlternativesRoute
  '/examples/add-item-and-scroll-to-it': typeof ExamplesAddItemAndScrollToItRoute
  '/examples/add-items': typeof ExamplesAddItemsRoute
  '/examples/autoplay': typeof ExamplesAutoplayRoute
  '/examples/bottom-arrows': typeof ExamplesBottomArrowsRoute
  '/examples/center-on-click': typeof ExamplesCenterOnClickRoute
  '/examples/custom-transition': typeof ExamplesCustomTransitionRoute
  '/examples/infinite-loop': typeof ExamplesInfiniteLoopRoute
  '/examples/items-animation': typeof ExamplesItemsAnimationRoute
  '/examples/mobile-swipe-only': typeof ExamplesMobileSwipeOnlyRoute
  '/examples/mouse-drag': typeof ExamplesMouseDragRoute
  '/examples/mui-scrollable-tabs': typeof ExamplesMuiScrollableTabsRoute
  '/examples/one-item': typeof ExamplesOneItemRoute
  '/examples/one-item-scroll': typeof ExamplesOneItemScrollRoute
  '/examples/performance': typeof ExamplesPerformanceRoute
  '/examples/prevent-body-scroll': typeof ExamplesPreventBodyScrollRoute
  '/examples/progress': typeof ExamplesProgressRoute
  '/examples/rtl': typeof ExamplesRtlRoute
  '/examples/save-restore-position': typeof ExamplesSaveRestorePositionRoute
  '/examples/scroll-to-item': typeof ExamplesScrollToItemRoute
  '/examples/simple': typeof ExamplesSimpleRoute
  '/examples/swipe-desktop': typeof ExamplesSwipeDesktopRoute
  '/examples/vertical': typeof ExamplesVerticalRoute
  '/$locale': typeof LocaleIndexRoute
  '/examples': typeof ExamplesIndexRoute
  '/$locale/compare/embla-vs-swiper': typeof LocaleCompareEmblaVsSwiperRoute
  '/$locale/compare/react-slick-alternatives': typeof LocaleCompareReactSlickAlternativesRoute
  '/$locale/compare/swiper-alternatives': typeof LocaleCompareSwiperAlternativesRoute
  '/$locale/examples/add-item-and-scroll-to-it': typeof LocaleExamplesAddItemAndScrollToItRoute
  '/$locale/examples/add-items': typeof LocaleExamplesAddItemsRoute
  '/$locale/examples/autoplay': typeof LocaleExamplesAutoplayRoute
  '/$locale/examples/bottom-arrows': typeof LocaleExamplesBottomArrowsRoute
  '/$locale/examples/center-on-click': typeof LocaleExamplesCenterOnClickRoute
  '/$locale/examples/custom-transition': typeof LocaleExamplesCustomTransitionRoute
  '/$locale/examples/infinite-loop': typeof LocaleExamplesInfiniteLoopRoute
  '/$locale/examples/items-animation': typeof LocaleExamplesItemsAnimationRoute
  '/$locale/examples/mobile-swipe-only': typeof LocaleExamplesMobileSwipeOnlyRoute
  '/$locale/examples/mouse-drag': typeof LocaleExamplesMouseDragRoute
  '/$locale/examples/mui-scrollable-tabs': typeof LocaleExamplesMuiScrollableTabsRoute
  '/$locale/examples/one-item': typeof LocaleExamplesOneItemRoute
  '/$locale/examples/one-item-scroll': typeof LocaleExamplesOneItemScrollRoute
  '/$locale/examples/performance': typeof LocaleExamplesPerformanceRoute
  '/$locale/examples/prevent-body-scroll': typeof LocaleExamplesPreventBodyScrollRoute
  '/$locale/examples/progress': typeof LocaleExamplesProgressRoute
  '/$locale/examples/rtl': typeof LocaleExamplesRtlRoute
  '/$locale/examples/save-restore-position': typeof LocaleExamplesSaveRestorePositionRoute
  '/$locale/examples/scroll-to-item': typeof LocaleExamplesScrollToItemRoute
  '/$locale/examples/simple': typeof LocaleExamplesSimpleRoute
  '/$locale/examples/swipe-desktop': typeof LocaleExamplesSwipeDesktopRoute
  '/$locale/examples/vertical': typeof LocaleExamplesVerticalRoute
  '/$locale/examples': typeof LocaleExamplesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/category-rail': typeof CategoryRailRoute
  '/compare': typeof CompareRoute
  '/filter-chips': typeof FilterChipsRoute
  '/netflix-row': typeof NetflixRowRoute
  '/scrollable-tabs': typeof ScrollableTabsRoute
  '/$locale/category-rail': typeof LocaleCategoryRailRoute
  '/$locale/compare': typeof LocaleCompareRoute
  '/$locale/filter-chips': typeof LocaleFilterChipsRoute
  '/$locale/netflix-row': typeof LocaleNetflixRowRoute
  '/$locale/scrollable-tabs': typeof LocaleScrollableTabsRoute
  '/compare_/embla-vs-swiper': typeof CompareEmblaVsSwiperRoute
  '/compare_/react-slick-alternatives': typeof CompareReactSlickAlternativesRoute
  '/compare_/swiper-alternatives': typeof CompareSwiperAlternativesRoute
  '/examples/add-item-and-scroll-to-it': typeof ExamplesAddItemAndScrollToItRoute
  '/examples/add-items': typeof ExamplesAddItemsRoute
  '/examples/autoplay': typeof ExamplesAutoplayRoute
  '/examples/bottom-arrows': typeof ExamplesBottomArrowsRoute
  '/examples/center-on-click': typeof ExamplesCenterOnClickRoute
  '/examples/custom-transition': typeof ExamplesCustomTransitionRoute
  '/examples/infinite-loop': typeof ExamplesInfiniteLoopRoute
  '/examples/items-animation': typeof ExamplesItemsAnimationRoute
  '/examples/mobile-swipe-only': typeof ExamplesMobileSwipeOnlyRoute
  '/examples/mouse-drag': typeof ExamplesMouseDragRoute
  '/examples/mui-scrollable-tabs': typeof ExamplesMuiScrollableTabsRoute
  '/examples/one-item': typeof ExamplesOneItemRoute
  '/examples/one-item-scroll': typeof ExamplesOneItemScrollRoute
  '/examples/performance': typeof ExamplesPerformanceRoute
  '/examples/prevent-body-scroll': typeof ExamplesPreventBodyScrollRoute
  '/examples/progress': typeof ExamplesProgressRoute
  '/examples/rtl': typeof ExamplesRtlRoute
  '/examples/save-restore-position': typeof ExamplesSaveRestorePositionRoute
  '/examples/scroll-to-item': typeof ExamplesScrollToItemRoute
  '/examples/simple': typeof ExamplesSimpleRoute
  '/examples/swipe-desktop': typeof ExamplesSwipeDesktopRoute
  '/examples/vertical': typeof ExamplesVerticalRoute
  '/$locale/': typeof LocaleIndexRoute
  '/examples/': typeof ExamplesIndexRoute
  '/$locale/compare_/embla-vs-swiper': typeof LocaleCompareEmblaVsSwiperRoute
  '/$locale/compare_/react-slick-alternatives': typeof LocaleCompareReactSlickAlternativesRoute
  '/$locale/compare_/swiper-alternatives': typeof LocaleCompareSwiperAlternativesRoute
  '/$locale/examples/add-item-and-scroll-to-it': typeof LocaleExamplesAddItemAndScrollToItRoute
  '/$locale/examples/add-items': typeof LocaleExamplesAddItemsRoute
  '/$locale/examples/autoplay': typeof LocaleExamplesAutoplayRoute
  '/$locale/examples/bottom-arrows': typeof LocaleExamplesBottomArrowsRoute
  '/$locale/examples/center-on-click': typeof LocaleExamplesCenterOnClickRoute
  '/$locale/examples/custom-transition': typeof LocaleExamplesCustomTransitionRoute
  '/$locale/examples/infinite-loop': typeof LocaleExamplesInfiniteLoopRoute
  '/$locale/examples/items-animation': typeof LocaleExamplesItemsAnimationRoute
  '/$locale/examples/mobile-swipe-only': typeof LocaleExamplesMobileSwipeOnlyRoute
  '/$locale/examples/mouse-drag': typeof LocaleExamplesMouseDragRoute
  '/$locale/examples/mui-scrollable-tabs': typeof LocaleExamplesMuiScrollableTabsRoute
  '/$locale/examples/one-item': typeof LocaleExamplesOneItemRoute
  '/$locale/examples/one-item-scroll': typeof LocaleExamplesOneItemScrollRoute
  '/$locale/examples/performance': typeof LocaleExamplesPerformanceRoute
  '/$locale/examples/prevent-body-scroll': typeof LocaleExamplesPreventBodyScrollRoute
  '/$locale/examples/progress': typeof LocaleExamplesProgressRoute
  '/$locale/examples/rtl': typeof LocaleExamplesRtlRoute
  '/$locale/examples/save-restore-position': typeof LocaleExamplesSaveRestorePositionRoute
  '/$locale/examples/scroll-to-item': typeof LocaleExamplesScrollToItemRoute
  '/$locale/examples/simple': typeof LocaleExamplesSimpleRoute
  '/$locale/examples/swipe-desktop': typeof LocaleExamplesSwipeDesktopRoute
  '/$locale/examples/vertical': typeof LocaleExamplesVerticalRoute
  '/$locale/examples/': typeof LocaleExamplesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/category-rail'
    | '/compare'
    | '/filter-chips'
    | '/netflix-row'
    | '/scrollable-tabs'
    | '/$locale/category-rail'
    | '/$locale/compare'
    | '/$locale/filter-chips'
    | '/$locale/netflix-row'
    | '/$locale/scrollable-tabs'
    | '/compare/embla-vs-swiper'
    | '/compare/react-slick-alternatives'
    | '/compare/swiper-alternatives'
    | '/examples/add-item-and-scroll-to-it'
    | '/examples/add-items'
    | '/examples/autoplay'
    | '/examples/bottom-arrows'
    | '/examples/center-on-click'
    | '/examples/custom-transition'
    | '/examples/infinite-loop'
    | '/examples/items-animation'
    | '/examples/mobile-swipe-only'
    | '/examples/mouse-drag'
    | '/examples/mui-scrollable-tabs'
    | '/examples/one-item'
    | '/examples/one-item-scroll'
    | '/examples/performance'
    | '/examples/prevent-body-scroll'
    | '/examples/progress'
    | '/examples/rtl'
    | '/examples/save-restore-position'
    | '/examples/scroll-to-item'
    | '/examples/simple'
    | '/examples/swipe-desktop'
    | '/examples/vertical'
    | '/$locale/'
    | '/examples/'
    | '/$locale/compare/embla-vs-swiper'
    | '/$locale/compare/react-slick-alternatives'
    | '/$locale/compare/swiper-alternatives'
    | '/$locale/examples/add-item-and-scroll-to-it'
    | '/$locale/examples/add-items'
    | '/$locale/examples/autoplay'
    | '/$locale/examples/bottom-arrows'
    | '/$locale/examples/center-on-click'
    | '/$locale/examples/custom-transition'
    | '/$locale/examples/infinite-loop'
    | '/$locale/examples/items-animation'
    | '/$locale/examples/mobile-swipe-only'
    | '/$locale/examples/mouse-drag'
    | '/$locale/examples/mui-scrollable-tabs'
    | '/$locale/examples/one-item'
    | '/$locale/examples/one-item-scroll'
    | '/$locale/examples/performance'
    | '/$locale/examples/prevent-body-scroll'
    | '/$locale/examples/progress'
    | '/$locale/examples/rtl'
    | '/$locale/examples/save-restore-position'
    | '/$locale/examples/scroll-to-item'
    | '/$locale/examples/simple'
    | '/$locale/examples/swipe-desktop'
    | '/$locale/examples/vertical'
    | '/$locale/examples/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/category-rail'
    | '/compare'
    | '/filter-chips'
    | '/netflix-row'
    | '/scrollable-tabs'
    | '/$locale/category-rail'
    | '/$locale/compare'
    | '/$locale/filter-chips'
    | '/$locale/netflix-row'
    | '/$locale/scrollable-tabs'
    | '/compare/embla-vs-swiper'
    | '/compare/react-slick-alternatives'
    | '/compare/swiper-alternatives'
    | '/examples/add-item-and-scroll-to-it'
    | '/examples/add-items'
    | '/examples/autoplay'
    | '/examples/bottom-arrows'
    | '/examples/center-on-click'
    | '/examples/custom-transition'
    | '/examples/infinite-loop'
    | '/examples/items-animation'
    | '/examples/mobile-swipe-only'
    | '/examples/mouse-drag'
    | '/examples/mui-scrollable-tabs'
    | '/examples/one-item'
    | '/examples/one-item-scroll'
    | '/examples/performance'
    | '/examples/prevent-body-scroll'
    | '/examples/progress'
    | '/examples/rtl'
    | '/examples/save-restore-position'
    | '/examples/scroll-to-item'
    | '/examples/simple'
    | '/examples/swipe-desktop'
    | '/examples/vertical'
    | '/$locale'
    | '/examples'
    | '/$locale/compare/embla-vs-swiper'
    | '/$locale/compare/react-slick-alternatives'
    | '/$locale/compare/swiper-alternatives'
    | '/$locale/examples/add-item-and-scroll-to-it'
    | '/$locale/examples/add-items'
    | '/$locale/examples/autoplay'
    | '/$locale/examples/bottom-arrows'
    | '/$locale/examples/center-on-click'
    | '/$locale/examples/custom-transition'
    | '/$locale/examples/infinite-loop'
    | '/$locale/examples/items-animation'
    | '/$locale/examples/mobile-swipe-only'
    | '/$locale/examples/mouse-drag'
    | '/$locale/examples/mui-scrollable-tabs'
    | '/$locale/examples/one-item'
    | '/$locale/examples/one-item-scroll'
    | '/$locale/examples/performance'
    | '/$locale/examples/prevent-body-scroll'
    | '/$locale/examples/progress'
    | '/$locale/examples/rtl'
    | '/$locale/examples/save-restore-position'
    | '/$locale/examples/scroll-to-item'
    | '/$locale/examples/simple'
    | '/$locale/examples/swipe-desktop'
    | '/$locale/examples/vertical'
    | '/$locale/examples'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/category-rail'
    | '/compare'
    | '/filter-chips'
    | '/netflix-row'
    | '/scrollable-tabs'
    | '/$locale/category-rail'
    | '/$locale/compare'
    | '/$locale/filter-chips'
    | '/$locale/netflix-row'
    | '/$locale/scrollable-tabs'
    | '/compare_/embla-vs-swiper'
    | '/compare_/react-slick-alternatives'
    | '/compare_/swiper-alternatives'
    | '/examples/add-item-and-scroll-to-it'
    | '/examples/add-items'
    | '/examples/autoplay'
    | '/examples/bottom-arrows'
    | '/examples/center-on-click'
    | '/examples/custom-transition'
    | '/examples/infinite-loop'
    | '/examples/items-animation'
    | '/examples/mobile-swipe-only'
    | '/examples/mouse-drag'
    | '/examples/mui-scrollable-tabs'
    | '/examples/one-item'
    | '/examples/one-item-scroll'
    | '/examples/performance'
    | '/examples/prevent-body-scroll'
    | '/examples/progress'
    | '/examples/rtl'
    | '/examples/save-restore-position'
    | '/examples/scroll-to-item'
    | '/examples/simple'
    | '/examples/swipe-desktop'
    | '/examples/vertical'
    | '/$locale/'
    | '/examples/'
    | '/$locale/compare_/embla-vs-swiper'
    | '/$locale/compare_/react-slick-alternatives'
    | '/$locale/compare_/swiper-alternatives'
    | '/$locale/examples/add-item-and-scroll-to-it'
    | '/$locale/examples/add-items'
    | '/$locale/examples/autoplay'
    | '/$locale/examples/bottom-arrows'
    | '/$locale/examples/center-on-click'
    | '/$locale/examples/custom-transition'
    | '/$locale/examples/infinite-loop'
    | '/$locale/examples/items-animation'
    | '/$locale/examples/mobile-swipe-only'
    | '/$locale/examples/mouse-drag'
    | '/$locale/examples/mui-scrollable-tabs'
    | '/$locale/examples/one-item'
    | '/$locale/examples/one-item-scroll'
    | '/$locale/examples/performance'
    | '/$locale/examples/prevent-body-scroll'
    | '/$locale/examples/progress'
    | '/$locale/examples/rtl'
    | '/$locale/examples/save-restore-position'
    | '/$locale/examples/scroll-to-item'
    | '/$locale/examples/simple'
    | '/$locale/examples/swipe-desktop'
    | '/$locale/examples/vertical'
    | '/$locale/examples/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  CategoryRailRoute: typeof CategoryRailRoute
  CompareRoute: typeof CompareRoute
  FilterChipsRoute: typeof FilterChipsRoute
  NetflixRowRoute: typeof NetflixRowRoute
  ScrollableTabsRoute: typeof ScrollableTabsRoute
  CompareEmblaVsSwiperRoute: typeof CompareEmblaVsSwiperRoute
  CompareReactSlickAlternativesRoute: typeof CompareReactSlickAlternativesRoute
  CompareSwiperAlternativesRoute: typeof CompareSwiperAlternativesRoute
  ExamplesAddItemAndScrollToItRoute: typeof ExamplesAddItemAndScrollToItRoute
  ExamplesAddItemsRoute: typeof ExamplesAddItemsRoute
  ExamplesAutoplayRoute: typeof ExamplesAutoplayRoute
  ExamplesBottomArrowsRoute: typeof ExamplesBottomArrowsRoute
  ExamplesCenterOnClickRoute: typeof ExamplesCenterOnClickRoute
  ExamplesCustomTransitionRoute: typeof ExamplesCustomTransitionRoute
  ExamplesInfiniteLoopRoute: typeof ExamplesInfiniteLoopRoute
  ExamplesItemsAnimationRoute: typeof ExamplesItemsAnimationRoute
  ExamplesMobileSwipeOnlyRoute: typeof ExamplesMobileSwipeOnlyRoute
  ExamplesMouseDragRoute: typeof ExamplesMouseDragRoute
  ExamplesMuiScrollableTabsRoute: typeof ExamplesMuiScrollableTabsRoute
  ExamplesOneItemRoute: typeof ExamplesOneItemRoute
  ExamplesOneItemScrollRoute: typeof ExamplesOneItemScrollRoute
  ExamplesPerformanceRoute: typeof ExamplesPerformanceRoute
  ExamplesPreventBodyScrollRoute: typeof ExamplesPreventBodyScrollRoute
  ExamplesProgressRoute: typeof ExamplesProgressRoute
  ExamplesRtlRoute: typeof ExamplesRtlRoute
  ExamplesSaveRestorePositionRoute: typeof ExamplesSaveRestorePositionRoute
  ExamplesScrollToItemRoute: typeof ExamplesScrollToItemRoute
  ExamplesSimpleRoute: typeof ExamplesSimpleRoute
  ExamplesSwipeDesktopRoute: typeof ExamplesSwipeDesktopRoute
  ExamplesVerticalRoute: typeof ExamplesVerticalRoute
  ExamplesIndexRoute: typeof ExamplesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category-rail': {
      id: '/category-rail'
      path: '/category-rail'
      fullPath: '/category-rail'
      preLoaderRoute: typeof CategoryRailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filter-chips': {
      id: '/filter-chips'
      path: '/filter-chips'
      fullPath: '/filter-chips'
      preLoaderRoute: typeof FilterChipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/netflix-row': {
      id: '/netflix-row'
      path: '/netflix-row'
      fullPath: '/netflix-row'
      preLoaderRoute: typeof NetflixRowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scrollable-tabs': {
      id: '/scrollable-tabs'
      path: '/scrollable-tabs'
      fullPath: '/scrollable-tabs'
      preLoaderRoute: typeof ScrollableTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/category-rail': {
      id: '/$locale/category-rail'
      path: '/category-rail'
      fullPath: '/$locale/category-rail'
      preLoaderRoute: typeof LocaleCategoryRailRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/compare': {
      id: '/$locale/compare'
      path: '/compare'
      fullPath: '/$locale/compare'
      preLoaderRoute: typeof LocaleCompareRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/filter-chips': {
      id: '/$locale/filter-chips'
      path: '/filter-chips'
      fullPath: '/$locale/filter-chips'
      preLoaderRoute: typeof LocaleFilterChipsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/netflix-row': {
      id: '/$locale/netflix-row'
      path: '/netflix-row'
      fullPath: '/$locale/netflix-row'
      preLoaderRoute: typeof LocaleNetflixRowRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/scrollable-tabs': {
      id: '/$locale/scrollable-tabs'
      path: '/scrollable-tabs'
      fullPath: '/$locale/scrollable-tabs'
      preLoaderRoute: typeof LocaleScrollableTabsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/compare_/embla-vs-swiper': {
      id: '/compare_/embla-vs-swiper'
      path: '/compare/embla-vs-swiper'
      fullPath: '/compare/embla-vs-swiper'
      preLoaderRoute: typeof CompareEmblaVsSwiperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare_/react-slick-alternatives': {
      id: '/compare_/react-slick-alternatives'
      path: '/compare/react-slick-alternatives'
      fullPath: '/compare/react-slick-alternatives'
      preLoaderRoute: typeof CompareReactSlickAlternativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare_/swiper-alternatives': {
      id: '/compare_/swiper-alternatives'
      path: '/compare/swiper-alternatives'
      fullPath: '/compare/swiper-alternatives'
      preLoaderRoute: typeof CompareSwiperAlternativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/': {
      id: '/examples/'
      path: '/examples'
      fullPath: '/examples/'
      preLoaderRoute: typeof ExamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/add-item-and-scroll-to-it': {
      id: '/examples/add-item-and-scroll-to-it'
      path: '/examples/add-item-and-scroll-to-it'
      fullPath: '/examples/add-item-and-scroll-to-it'
      preLoaderRoute: typeof ExamplesAddItemAndScrollToItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/add-items': {
      id: '/examples/add-items'
      path: '/examples/add-items'
      fullPath: '/examples/add-items'
      preLoaderRoute: typeof ExamplesAddItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/autoplay': {
      id: '/examples/autoplay'
      path: '/examples/autoplay'
      fullPath: '/examples/autoplay'
      preLoaderRoute: typeof ExamplesAutoplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/bottom-arrows': {
      id: '/examples/bottom-arrows'
      path: '/examples/bottom-arrows'
      fullPath: '/examples/bottom-arrows'
      preLoaderRoute: typeof ExamplesBottomArrowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/center-on-click': {
      id: '/examples/center-on-click'
      path: '/examples/center-on-click'
      fullPath: '/examples/center-on-click'
      preLoaderRoute: typeof ExamplesCenterOnClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/custom-transition': {
      id: '/examples/custom-transition'
      path: '/examples/custom-transition'
      fullPath: '/examples/custom-transition'
      preLoaderRoute: typeof ExamplesCustomTransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/infinite-loop': {
      id: '/examples/infinite-loop'
      path: '/examples/infinite-loop'
      fullPath: '/examples/infinite-loop'
      preLoaderRoute: typeof ExamplesInfiniteLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/items-animation': {
      id: '/examples/items-animation'
      path: '/examples/items-animation'
      fullPath: '/examples/items-animation'
      preLoaderRoute: typeof ExamplesItemsAnimationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/mobile-swipe-only': {
      id: '/examples/mobile-swipe-only'
      path: '/examples/mobile-swipe-only'
      fullPath: '/examples/mobile-swipe-only'
      preLoaderRoute: typeof ExamplesMobileSwipeOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/mouse-drag': {
      id: '/examples/mouse-drag'
      path: '/examples/mouse-drag'
      fullPath: '/examples/mouse-drag'
      preLoaderRoute: typeof ExamplesMouseDragRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/mui-scrollable-tabs': {
      id: '/examples/mui-scrollable-tabs'
      path: '/examples/mui-scrollable-tabs'
      fullPath: '/examples/mui-scrollable-tabs'
      preLoaderRoute: typeof ExamplesMuiScrollableTabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/one-item': {
      id: '/examples/one-item'
      path: '/examples/one-item'
      fullPath: '/examples/one-item'
      preLoaderRoute: typeof ExamplesOneItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/one-item-scroll': {
      id: '/examples/one-item-scroll'
      path: '/examples/one-item-scroll'
      fullPath: '/examples/one-item-scroll'
      preLoaderRoute: typeof ExamplesOneItemScrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/performance': {
      id: '/examples/performance'
      path: '/examples/performance'
      fullPath: '/examples/performance'
      preLoaderRoute: typeof ExamplesPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/prevent-body-scroll': {
      id: '/examples/prevent-body-scroll'
      path: '/examples/prevent-body-scroll'
      fullPath: '/examples/prevent-body-scroll'
      preLoaderRoute: typeof ExamplesPreventBodyScrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/progress': {
      id: '/examples/progress'
      path: '/examples/progress'
      fullPath: '/examples/progress'
      preLoaderRoute: typeof ExamplesProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/rtl': {
      id: '/examples/rtl'
      path: '/examples/rtl'
      fullPath: '/examples/rtl'
      preLoaderRoute: typeof ExamplesRtlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/save-restore-position': {
      id: '/examples/save-restore-position'
      path: '/examples/save-restore-position'
      fullPath: '/examples/save-restore-position'
      preLoaderRoute: typeof ExamplesSaveRestorePositionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/scroll-to-item': {
      id: '/examples/scroll-to-item'
      path: '/examples/scroll-to-item'
      fullPath: '/examples/scroll-to-item'
      preLoaderRoute: typeof ExamplesScrollToItemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/simple': {
      id: '/examples/simple'
      path: '/examples/simple'
      fullPath: '/examples/simple'
      preLoaderRoute: typeof ExamplesSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/swipe-desktop': {
      id: '/examples/swipe-desktop'
      path: '/examples/swipe-desktop'
      fullPath: '/examples/swipe-desktop'
      preLoaderRoute: typeof ExamplesSwipeDesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/vertical': {
      id: '/examples/vertical'
      path: '/examples/vertical'
      fullPath: '/examples/vertical'
      preLoaderRoute: typeof ExamplesVerticalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/compare_/embla-vs-swiper': {
      id: '/$locale/compare_/embla-vs-swiper'
      path: '/compare/embla-vs-swiper'
      fullPath: '/$locale/compare/embla-vs-swiper'
      preLoaderRoute: typeof LocaleCompareEmblaVsSwiperRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/compare_/react-slick-alternatives': {
      id: '/$locale/compare_/react-slick-alternatives'
      path: '/compare/react-slick-alternatives'
      fullPath: '/$locale/compare/react-slick-alternatives'
      preLoaderRoute: typeof LocaleCompareReactSlickAlternativesRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/compare_/swiper-alternatives': {
      id: '/$locale/compare_/swiper-alternatives'
      path: '/compare/swiper-alternatives'
      fullPath: '/$locale/compare/swiper-alternatives'
      preLoaderRoute: typeof LocaleCompareSwiperAlternativesRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/': {
      id: '/$locale/examples/'
      path: '/examples'
      fullPath: '/$locale/examples/'
      preLoaderRoute: typeof LocaleExamplesIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/add-item-and-scroll-to-it': {
      id: '/$locale/examples/add-item-and-scroll-to-it'
      path: '/examples/add-item-and-scroll-to-it'
      fullPath: '/$locale/examples/add-item-and-scroll-to-it'
      preLoaderRoute: typeof LocaleExamplesAddItemAndScrollToItRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/add-items': {
      id: '/$locale/examples/add-items'
      path: '/examples/add-items'
      fullPath: '/$locale/examples/add-items'
      preLoaderRoute: typeof LocaleExamplesAddItemsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/autoplay': {
      id: '/$locale/examples/autoplay'
      path: '/examples/autoplay'
      fullPath: '/$locale/examples/autoplay'
      preLoaderRoute: typeof LocaleExamplesAutoplayRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/bottom-arrows': {
      id: '/$locale/examples/bottom-arrows'
      path: '/examples/bottom-arrows'
      fullPath: '/$locale/examples/bottom-arrows'
      preLoaderRoute: typeof LocaleExamplesBottomArrowsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/center-on-click': {
      id: '/$locale/examples/center-on-click'
      path: '/examples/center-on-click'
      fullPath: '/$locale/examples/center-on-click'
      preLoaderRoute: typeof LocaleExamplesCenterOnClickRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/custom-transition': {
      id: '/$locale/examples/custom-transition'
      path: '/examples/custom-transition'
      fullPath: '/$locale/examples/custom-transition'
      preLoaderRoute: typeof LocaleExamplesCustomTransitionRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/infinite-loop': {
      id: '/$locale/examples/infinite-loop'
      path: '/examples/infinite-loop'
      fullPath: '/$locale/examples/infinite-loop'
      preLoaderRoute: typeof LocaleExamplesInfiniteLoopRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/items-animation': {
      id: '/$locale/examples/items-animation'
      path: '/examples/items-animation'
      fullPath: '/$locale/examples/items-animation'
      preLoaderRoute: typeof LocaleExamplesItemsAnimationRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/mobile-swipe-only': {
      id: '/$locale/examples/mobile-swipe-only'
      path: '/examples/mobile-swipe-only'
      fullPath: '/$locale/examples/mobile-swipe-only'
      preLoaderRoute: typeof LocaleExamplesMobileSwipeOnlyRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/mouse-drag': {
      id: '/$locale/examples/mouse-drag'
      path: '/examples/mouse-drag'
      fullPath: '/$locale/examples/mouse-drag'
      preLoaderRoute: typeof LocaleExamplesMouseDragRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/mui-scrollable-tabs': {
      id: '/$locale/examples/mui-scrollable-tabs'
      path: '/examples/mui-scrollable-tabs'
      fullPath: '/$locale/examples/mui-scrollable-tabs'
      preLoaderRoute: typeof LocaleExamplesMuiScrollableTabsRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/one-item': {
      id: '/$locale/examples/one-item'
      path: '/examples/one-item'
      fullPath: '/$locale/examples/one-item'
      preLoaderRoute: typeof LocaleExamplesOneItemRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/one-item-scroll': {
      id: '/$locale/examples/one-item-scroll'
      path: '/examples/one-item-scroll'
      fullPath: '/$locale/examples/one-item-scroll'
      preLoaderRoute: typeof LocaleExamplesOneItemScrollRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/performance': {
      id: '/$locale/examples/performance'
      path: '/examples/performance'
      fullPath: '/$locale/examples/performance'
      preLoaderRoute: typeof LocaleExamplesPerformanceRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/prevent-body-scroll': {
      id: '/$locale/examples/prevent-body-scroll'
      path: '/examples/prevent-body-scroll'
      fullPath: '/$locale/examples/prevent-body-scroll'
      preLoaderRoute: typeof LocaleExamplesPreventBodyScrollRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/progress': {
      id: '/$locale/examples/progress'
      path: '/examples/progress'
      fullPath: '/$locale/examples/progress'
      preLoaderRoute: typeof LocaleExamplesProgressRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/rtl': {
      id: '/$locale/examples/rtl'
      path: '/examples/rtl'
      fullPath: '/$locale/examples/rtl'
      preLoaderRoute: typeof LocaleExamplesRtlRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/save-restore-position': {
      id: '/$locale/examples/save-restore-position'
      path: '/examples/save-restore-position'
      fullPath: '/$locale/examples/save-restore-position'
      preLoaderRoute: typeof LocaleExamplesSaveRestorePositionRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/scroll-to-item': {
      id: '/$locale/examples/scroll-to-item'
      path: '/examples/scroll-to-item'
      fullPath: '/$locale/examples/scroll-to-item'
      preLoaderRoute: typeof LocaleExamplesScrollToItemRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/simple': {
      id: '/$locale/examples/simple'
      path: '/examples/simple'
      fullPath: '/$locale/examples/simple'
      preLoaderRoute: typeof LocaleExamplesSimpleRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/swipe-desktop': {
      id: '/$locale/examples/swipe-desktop'
      path: '/examples/swipe-desktop'
      fullPath: '/$locale/examples/swipe-desktop'
      preLoaderRoute: typeof LocaleExamplesSwipeDesktopRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/examples/vertical': {
      id: '/$locale/examples/vertical'
      path: '/examples/vertical'
      fullPath: '/$locale/examples/vertical'
      preLoaderRoute: typeof LocaleExamplesVerticalRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleCategoryRailRoute: typeof LocaleCategoryRailRoute
  LocaleCompareRoute: typeof LocaleCompareRoute
  LocaleFilterChipsRoute: typeof LocaleFilterChipsRoute
  LocaleNetflixRowRoute: typeof LocaleNetflixRowRoute
  LocaleScrollableTabsRoute: typeof LocaleScrollableTabsRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleCompareEmblaVsSwiperRoute: typeof LocaleCompareEmblaVsSwiperRoute
  LocaleCompareReactSlickAlternativesRoute: typeof LocaleCompareReactSlickAlternativesRoute
  LocaleCompareSwiperAlternativesRoute: typeof LocaleCompareSwiperAlternativesRoute
  LocaleExamplesAddItemAndScrollToItRoute: typeof LocaleExamplesAddItemAndScrollToItRoute
  LocaleExamplesAddItemsRoute: typeof LocaleExamplesAddItemsRoute
  LocaleExamplesAutoplayRoute: typeof LocaleExamplesAutoplayRoute
  LocaleExamplesBottomArrowsRoute: typeof LocaleExamplesBottomArrowsRoute
  LocaleExamplesCenterOnClickRoute: typeof LocaleExamplesCenterOnClickRoute
  LocaleExamplesCustomTransitionRoute: typeof LocaleExamplesCustomTransitionRoute
  LocaleExamplesInfiniteLoopRoute: typeof LocaleExamplesInfiniteLoopRoute
  LocaleExamplesItemsAnimationRoute: typeof LocaleExamplesItemsAnimationRoute
  LocaleExamplesMobileSwipeOnlyRoute: typeof LocaleExamplesMobileSwipeOnlyRoute
  LocaleExamplesMouseDragRoute: typeof LocaleExamplesMouseDragRoute
  LocaleExamplesMuiScrollableTabsRoute: typeof LocaleExamplesMuiScrollableTabsRoute
  LocaleExamplesOneItemRoute: typeof LocaleExamplesOneItemRoute
  LocaleExamplesOneItemScrollRoute: typeof LocaleExamplesOneItemScrollRoute
  LocaleExamplesPerformanceRoute: typeof LocaleExamplesPerformanceRoute
  LocaleExamplesPreventBodyScrollRoute: typeof LocaleExamplesPreventBodyScrollRoute
  LocaleExamplesProgressRoute: typeof LocaleExamplesProgressRoute
  LocaleExamplesRtlRoute: typeof LocaleExamplesRtlRoute
  LocaleExamplesSaveRestorePositionRoute: typeof LocaleExamplesSaveRestorePositionRoute
  LocaleExamplesScrollToItemRoute: typeof LocaleExamplesScrollToItemRoute
  LocaleExamplesSimpleRoute: typeof LocaleExamplesSimpleRoute
  LocaleExamplesSwipeDesktopRoute: typeof LocaleExamplesSwipeDesktopRoute
  LocaleExamplesVerticalRoute: typeof LocaleExamplesVerticalRoute
  LocaleExamplesIndexRoute: typeof LocaleExamplesIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleCategoryRailRoute: LocaleCategoryRailRoute,
  LocaleCompareRoute: LocaleCompareRoute,
  LocaleFilterChipsRoute: LocaleFilterChipsRoute,
  LocaleNetflixRowRoute: LocaleNetflixRowRoute,
  LocaleScrollableTabsRoute: LocaleScrollableTabsRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleCompareEmblaVsSwiperRoute: LocaleCompareEmblaVsSwiperRoute,
  LocaleCompareReactSlickAlternativesRoute:
    LocaleCompareReactSlickAlternativesRoute,
  LocaleCompareSwiperAlternativesRoute: LocaleCompareSwiperAlternativesRoute,
  LocaleExamplesAddItemAndScrollToItRoute:
    LocaleExamplesAddItemAndScrollToItRoute,
  LocaleExamplesAddItemsRoute: LocaleExamplesAddItemsRoute,
  LocaleExamplesAutoplayRoute: LocaleExamplesAutoplayRoute,
  LocaleExamplesBottomArrowsRoute: LocaleExamplesBottomArrowsRoute,
  LocaleExamplesCenterOnClickRoute: LocaleExamplesCenterOnClickRoute,
  LocaleExamplesCustomTransitionRoute: LocaleExamplesCustomTransitionRoute,
  LocaleExamplesInfiniteLoopRoute: LocaleExamplesInfiniteLoopRoute,
  LocaleExamplesItemsAnimationRoute: LocaleExamplesItemsAnimationRoute,
  LocaleExamplesMobileSwipeOnlyRoute: LocaleExamplesMobileSwipeOnlyRoute,
  LocaleExamplesMouseDragRoute: LocaleExamplesMouseDragRoute,
  LocaleExamplesMuiScrollableTabsRoute: LocaleExamplesMuiScrollableTabsRoute,
  LocaleExamplesOneItemRoute: LocaleExamplesOneItemRoute,
  LocaleExamplesOneItemScrollRoute: LocaleExamplesOneItemScrollRoute,
  LocaleExamplesPerformanceRoute: LocaleExamplesPerformanceRoute,
  LocaleExamplesPreventBodyScrollRoute: LocaleExamplesPreventBodyScrollRoute,
  LocaleExamplesProgressRoute: LocaleExamplesProgressRoute,
  LocaleExamplesRtlRoute: LocaleExamplesRtlRoute,
  LocaleExamplesSaveRestorePositionRoute:
    LocaleExamplesSaveRestorePositionRoute,
  LocaleExamplesScrollToItemRoute: LocaleExamplesScrollToItemRoute,
  LocaleExamplesSimpleRoute: LocaleExamplesSimpleRoute,
  LocaleExamplesSwipeDesktopRoute: LocaleExamplesSwipeDesktopRoute,
  LocaleExamplesVerticalRoute: LocaleExamplesVerticalRoute,
  LocaleExamplesIndexRoute: LocaleExamplesIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  CategoryRailRoute: CategoryRailRoute,
  CompareRoute: CompareRoute,
  FilterChipsRoute: FilterChipsRoute,
  NetflixRowRoute: NetflixRowRoute,
  ScrollableTabsRoute: ScrollableTabsRoute,
  CompareEmblaVsSwiperRoute: CompareEmblaVsSwiperRoute,
  CompareReactSlickAlternativesRoute: CompareReactSlickAlternativesRoute,
  CompareSwiperAlternativesRoute: CompareSwiperAlternativesRoute,
  ExamplesAddItemAndScrollToItRoute: ExamplesAddItemAndScrollToItRoute,
  ExamplesAddItemsRoute: ExamplesAddItemsRoute,
  ExamplesAutoplayRoute: ExamplesAutoplayRoute,
  ExamplesBottomArrowsRoute: ExamplesBottomArrowsRoute,
  ExamplesCenterOnClickRoute: ExamplesCenterOnClickRoute,
  ExamplesCustomTransitionRoute: ExamplesCustomTransitionRoute,
  ExamplesInfiniteLoopRoute: ExamplesInfiniteLoopRoute,
  ExamplesItemsAnimationRoute: ExamplesItemsAnimationRoute,
  ExamplesMobileSwipeOnlyRoute: ExamplesMobileSwipeOnlyRoute,
  ExamplesMouseDragRoute: ExamplesMouseDragRoute,
  ExamplesMuiScrollableTabsRoute: ExamplesMuiScrollableTabsRoute,
  ExamplesOneItemRoute: ExamplesOneItemRoute,
  ExamplesOneItemScrollRoute: ExamplesOneItemScrollRoute,
  ExamplesPerformanceRoute: ExamplesPerformanceRoute,
  ExamplesPreventBodyScrollRoute: ExamplesPreventBodyScrollRoute,
  ExamplesProgressRoute: ExamplesProgressRoute,
  ExamplesRtlRoute: ExamplesRtlRoute,
  ExamplesSaveRestorePositionRoute: ExamplesSaveRestorePositionRoute,
  ExamplesScrollToItemRoute: ExamplesScrollToItemRoute,
  ExamplesSimpleRoute: ExamplesSimpleRoute,
  ExamplesSwipeDesktopRoute: ExamplesSwipeDesktopRoute,
  ExamplesVerticalRoute: ExamplesVerticalRoute,
  ExamplesIndexRoute: ExamplesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
