#!/usr/bin/env node
// The site-copy half of the i18n tooling.
//
// The README puts the locale in a filename; the website puts it in a content
// directory. `website/src/content/en/` holds the English strings as typed
// modules, and each language is that same directory with translated values.
//
// Keeping it typed is the point. A translator working in Markdown can drop a
// section and only a reader notices; here a dropped key fails `tsc`, and the
// site does not build.
//
//   node scripts/i18n/copy.mjs init     create missing locale directories
//   node scripts/i18n/copy.mjs status   what is translated, what drifted
//   node scripts/i18n/copy.mjs check    validate; non-zero exit on problems
//   node scripts/i18n/copy.mjs diff <locale> [file]
//   node scripts/i18n/copy.mjs stamp <locale>

import { execFileSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import path from 'node:path';

import { blobHash } from './documents.mjs';
import { findLocale, LOCALES } from './locales.mjs';

const repoRoot = path.resolve(new URL('../..', import.meta.url).pathname);

/** English content directory, relative to the repo root. */
const SOURCE_DIR = 'website/src/content/en';
const targetDir = (locale) => `website/src/content/${locale.dir}`;

/**
 * `index.ts` is the barrel that assembles a `SiteCopy`. It is generated per
 * locale rather than copied, because its imports are the same but its exported
 * const name is not.
 */
const BARREL = 'index.ts';

const args = process.argv.slice(2);
const command = args[0] ?? 'status';
const positional = args.slice(1).filter((a) => !a.startsWith('--'));
const flags = new Set(args.filter((a) => a.startsWith('--')));

const c = process.stdout.isTTY
  ? {
      dim: '\x1b[2m',
      red: '\x1b[31m',
      green: '\x1b[32m',
      yellow: '\x1b[33m',
      bold: '\x1b[1m',
      off: '\x1b[0m',
    }
  : { dim: '', red: '', green: '', yellow: '', bold: '', off: '' };

const sourceFiles = () =>
  readdirSync(path.join(repoRoot, SOURCE_DIR))
    .filter((f) => f.endsWith('.ts') && f !== BARREL)
    .sort();

const STAMP = /^\/\/ i18n:meta (.*)$/m;

function parseStamp(text) {
  const m = text.match(STAMP);
  if (!m) return null;
  const out = {};
  for (const pair of m[1].matchAll(/([\w-]+)=(\S+)/g)) out[pair[1]] = pair[2];
  return out;
}

function header(locale, file, blob, status) {
  return [
    `// ${locale.english} (${locale.code}) — translation of en/${file}.`,
    '//',
    '// Values only: every key, its order and its type come from the English',
    '// module, and a missing or renamed one is a type error rather than a',
    '// silently English page.',
    `// i18n:meta locale=${locale.code} source=en/${file} source-blob=${blob} status=${status}`,
    '',
  ].join('\n');
}

/** A module's body, minus any leading comment block. */
function bodyOf(text) {
  const lines = text.split('\n');
  let i = 0;
  while (
    i < lines.length &&
    (lines[i].startsWith('//') || lines[i].trim() === '')
  )
    i += 1;
  return lines.slice(i).join('\n');
}

/**
 * The per-locale barrel. Imports the same modules from its own directory and
 * exports the same `SiteCopy` shape under the locale's name.
 */
function barrelFor(locale, files) {
  const names = files.map((f) => f.replace(/\.ts$/, ''));
  const exportsOf = (name) =>
    name === 'examples-hub' ? ['examplePage', 'examplesHub'] : [name];
  const imports = names
    .map((name) => `import { ${exportsOf(name).join(', ')} } from './${name}';`)
    .sort()
    .join('\n');
  const keys = names.flatMap(exportsOf).sort();
  return [
    `// ${locale.english} (${locale.code}). Generated by scripts/i18n/copy.mjs.`,
    "import type { SiteCopy } from '../types';",
    imports,
    '',
    `export const ${camel(locale.dir)}: SiteCopy = {`,
    ...keys.map((k) => `  ${k},`),
    '};',
    '',
    `export default ${camel(locale.dir)};`,
    '',
  ].join('\n');
}

const camel = (dir) => dir.replace(/-([a-z])/g, (_, ch) => ch.toUpperCase());

function init() {
  const files = sourceFiles();
  let created = 0;
  for (const locale of LOCALES) {
    const dir = path.join(repoRoot, targetDir(locale));
    mkdirSync(dir, { recursive: true });

    for (const file of files) {
      const sourceRel = `${SOURCE_DIR}/${file}`;
      const abs = path.join(dir, file);
      const blob = blobHash(repoRoot, sourceRel);
      if (existsSync(abs)) {
        const text = readFileSync(abs, 'utf8');
        const stamp = parseStamp(text);
        writeFileSync(
          abs,
          header(
            locale,
            file,
            stamp?.['source-blob'] ?? blob,
            stamp?.status ?? 'pending',
          ) + bodyOf(text),
          'utf8',
        );
        continue;
      }
      const body = bodyOf(readFileSync(path.join(repoRoot, sourceRel), 'utf8'));
      writeFileSync(abs, header(locale, file, blob, 'pending') + body, 'utf8');
      created += 1;
    }

    writeFileSync(path.join(dir, BARREL), barrelFor(locale, files), 'utf8');
    console.log(
      `${c.green}+${c.off} website/src/content/${locale.dir}/ (${files.length} modules)`,
    );
  }
  console.log(
    created ? `\n${created} module(s) created.` : '\nNothing to create.',
  );
}

function report({ failOnPending }) {
  const files = sourceFiles();
  let problems = 0;
  let pending = 0;

  for (const locale of LOCALES) {
    const stale = [];
    let untranslated = 0;
    let missing = 0;

    for (const file of files) {
      const sourceRel = `${SOURCE_DIR}/${file}`;
      const abs = path.join(repoRoot, targetDir(locale), file);
      if (!existsSync(abs)) {
        missing += 1;
        continue;
      }
      const text = readFileSync(abs, 'utf8');
      const stamp = parseStamp(text);
      const blob = blobHash(repoRoot, sourceRel);
      if (!stamp) stale.push(`${file}: no stamp`);
      else if (stamp['source-blob'] !== blob) {
        stale.push(
          `${file}: from ${stamp['source-blob'].slice(0, 8)}, now ${blob.slice(0, 8)}`,
        );
      }
      if (
        bodyOf(text) ===
        bodyOf(readFileSync(path.join(repoRoot, sourceRel), 'utf8'))
      ) {
        untranslated += 1;
      }
    }

    problems += missing + stale.length;
    if (untranslated) pending += 1;
    const label = `  ${locale.code.padEnd(6)} ${locale.english.padEnd(22)}`;
    if (missing) {
      console.log(`${label} ${c.red}${missing} module(s) missing${c.off}`);
    } else if (stale.length) {
      console.log(`${label} ${c.red}${stale.length} stale${c.off}`);
      for (const s of stale.slice(0, 4))
        console.log(`         ${c.red}·${c.off} ${s}`);
    } else if (untranslated === files.length) {
      console.log(`${label} ${c.yellow}not translated yet${c.off}`);
    } else if (untranslated) {
      console.log(
        `${label} ${c.yellow}${untranslated}/${files.length} modules still English${c.off}`,
      );
    } else {
      console.log(`${label} ${c.green}ok${c.off}`);
    }
  }

  console.log(
    `\n${problems ? c.red : c.green}${problems} problem(s)${c.off}, ${c.yellow}${pending} locale(s) awaiting translation${c.off}.`,
  );
  console.log(
    `${c.dim}Key coverage is not checked here — \`tsc\` does it, and the build fails on a missing key.${c.off}`,
  );
  return problems + (failOnPending ? pending : 0);
}

function resolveLocale(input) {
  const locale = findLocale(input);
  if (!locale || locale.code === 'en') {
    console.error(
      `${c.red}Unknown locale "${input}". One of: ${LOCALES.map((l) => l.code).join(', ')}${c.off}`,
    );
    process.exit(2);
  }
  return locale;
}

function diff() {
  const locale = resolveLocale(positional[0]);
  const only = positional[1];
  for (const file of sourceFiles()) {
    if (only && file !== only) continue;
    const abs = path.join(repoRoot, targetDir(locale), file);
    if (!existsSync(abs)) continue;
    const stamp = parseStamp(readFileSync(abs, 'utf8'));
    const sourceRel = `${SOURCE_DIR}/${file}`;
    const current = blobHash(repoRoot, sourceRel);
    if (!stamp || stamp['source-blob'] === current) continue;

    console.log(
      `\n${c.bold}${file}: ${stamp['source-blob'].slice(0, 8)} → ${current.slice(0, 8)}${c.off}`,
    );
    let previous;
    try {
      previous = execFileSync(
        'git',
        ['cat-file', 'blob', stamp['source-blob']],
        {
          cwd: repoRoot,
          encoding: 'utf8',
        },
      );
    } catch {
      console.log(`${c.yellow}  blob not in this repo${c.off}`);
      continue;
    }
    const scratch = path.join(repoRoot, '.i18n-copy-diff.tmp');
    writeFileSync(scratch, previous, 'utf8');
    try {
      execFileSync(
        'git',
        [
          'diff',
          '--no-color',
          '--no-index',
          scratch,
          path.join(repoRoot, sourceRel),
        ],
        {
          cwd: repoRoot,
          stdio: ['ignore', 'inherit', 'inherit'],
        },
      );
    } catch (err) {
      if (err.status !== 1) throw err;
    } finally {
      rmSync(scratch, { force: true });
    }
  }
}

function stamp() {
  const locale = resolveLocale(positional[0]);
  let n = 0;
  for (const file of sourceFiles()) {
    const abs = path.join(repoRoot, targetDir(locale), file);
    if (!existsSync(abs)) continue;
    const text = readFileSync(abs, 'utf8');
    writeFileSync(
      abs,
      header(
        locale,
        file,
        blobHash(repoRoot, `${SOURCE_DIR}/${file}`),
        'translated',
      ) + bodyOf(text),
      'utf8',
    );
    n += 1;
  }
  console.log(
    `${c.green}✓${c.off} stamped ${n} ${locale.code} module(s) as current`,
  );
}

switch (command) {
  case 'init':
    init();
    break;
  case 'status':
    report({ failOnPending: false });
    break;
  case 'check':
    process.exitCode =
      report({ failOnPending: flags.has('--strict') }) > 0 ? 1 : 0;
    break;
  case 'diff':
    diff();
    break;
  case 'stamp':
    stamp();
    break;
  default:
    console.error(`Unknown command "${command}".`);
    process.exit(2);
}
