// Vietnamese (vi). Generated by scripts/i18n/copy.mjs.
import type { SiteCopy } from '../types.ts';
import { chrome } from './chrome.ts';
import { compare } from './compare.ts';
import { examples } from './examples.ts';
import { examplePage, examplesHub } from './examples-hub.ts';
import { home } from './home.ts';
import { manifest } from './manifest.ts';

export const vi: SiteCopy = {
  chrome,
  compare,
  examplePage,
  examples,
  examplesHub,
  home,
  manifest,
};

export default vi;
