export const rootClassName = 'react-horizontal-scrolling-menu'
export const separatorClassName = 'separator'
export const itemClassName = 'item'
export const menuItemsClassName = 'menu-items'
export const scrollContainerClassName = 'scroll-container'
