# This is a basic workflow to help you get started with Actionsname: PR Tasks Completed Check
name: 'PR Tasks Completed Check'

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  pull_request:
    types: [opened, edited]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: asmyshlyaev177/task-completed-checker-action@v0.1.3
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
