name: Add contributors
on:
  schedule:
    - cron:  '1 15 * * *'
  workflow_dispatch:
    inputs:
      name:
        description: 'Update contributors'
        required: false
        default: 'Thank all'
# push:
#   branches:
#     - main

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: BobAnkh/add-contributors@master
      with:
        REPO_NAME: 'asmyshlyaev177/react-horizontal-scrolling-menu'
        CONTRIBUTOR: '## Contributors'
        COLUMN_PER_ROW: '7'
        ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
        IMG_WIDTH: '70'
        FONT_SIZE: '12'
        PATH: '/README.md'
        COMMIT_MESSAGE: 'docs(README): update contributors'
        AVATAR_SHAPE: 'square'