name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    container: cypress/included:9.6.0

    env:
      CYPRESS_CACHE_FOLDER: ../cypress_cache
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install
        run: |
          mkdir -p ../cypress_cache && \
          yarn setup && \
          chmod -R 777 ../cypress_cache

      - name: Unit tests
        run: yarn test:unit -- --coverage --coverageReporters="lcov"

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        continue-on-error: true
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info

      - name: E2E tests
        uses: cypress-io/github-action@v2
        timeout-minutes: 30
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          env: true
          command: yarn test:e2e

      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress
          path: cypress
