name: Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-20.04
    container: cypress/included:cypress-13.4.0-node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

    env:
      CYPRESS_CACHE_FOLDER: ../cypress_cache
      NODE_OPTIONS: --max-old-space-size=4096
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI: true
      WIREIT_LOGGER: "simple"
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          check-latest: true
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - uses: google/wireit@setup-github-actions-caching/v1

      - name: Install
        run: |
          mkdir -p ../cypress_cache && \
          npm run setup && \
          chmod -R 777 ../cypress_cache && \
          npx cross-env HOME=/root npx playwright install chromium firefox --with-deps && \
          chmod -R 777 /root/.cache/ms-playwright

      - name: Types and linter check
        run: npm run test:lint

      - name: Unit tests
        run: npm run test:unit -- --coverage --coverageReporters="lcov"

      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        continue-on-error: true
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info

      - name: E2E tests builded version
        run: npm run test:e2e
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress
          path: cypress

      - name: E2E tests dev version
        run: npm run test:e2e:dev

      - name: Storybook tests
        run: npx cross-env HOME=/root npm run test:storybook

      - name: Build storybook
        run: npm run build-storybook

      - name: Deploy storybook
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - run: npm run setup && npm run build
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          provenance: true
